### ISSUE TITLE
Quordle

### ISSUE THREAD

**Issue by pac953** [aryan1107/aryan1107#1]
I play Quordle against hubby and sister. They always have the same words, but I sometimes have different words. Why?

**Comment by aryan1107** [comment]
Is your app version same as their?

**Comment by pac953** [comment]
As far as I know they are the same. I deleted my app and then downloaded it again.  Says 1.0. Sent from my iPhoneOn Jan 6, 2023, at 8:02 AM, Aryan Chaurasia ***@***.***> wrote:﻿
Is your app version same as their?

**Comment by pac953** [comment]
The only difference we can find is that I have downloaded the app and my sister goes to Quordle.comSent from my iPhoneOn Jan 6, 2023, at 11:35 AM, Patty Campbell ***@***.***> wrote:﻿As far as I know they are the same. I deleted my app and then downloaded it again.  Says 1.0. Sent from my iPhoneOn Jan 6, 2023, at 8:02 AM, Aryan Chaurasia ***@***.***> wrote:﻿
Is your app version same as their?

**Comment by aryan1107** [comment]
Ohh website server is different it has ads and phone it is different as I don't like ads. That's why they are different.
